// Dates already booked or blocked on the Airbnb calendar.
// Auto-generated by scripts/sync-availability.mjs - do not edit by hand.
// Each range is [checkin, checkout) - checkout day itself is free.
const BLOCKED_RANGES = [
  ["2026-08-18", "2026-08-29"],
  ["2026-09-04", "2026-09-12"],
];
