// Dates already booked or blocked on the Airbnb calendar.
// Auto-generated by scripts/sync-availability.mjs - do not edit by hand.
// Each range is [checkin, checkout) - checkout day itself is free.
const BLOCKED_RANGES = [

];
